### ISSUE TITLE
Error in installation horus

### ISSUE THREAD

**Issue by chrisho95** [kosctelecom/horus#4]
Hello,

I am trying to install Horus on a Freebsd VM and I get this error message. 

Cloning into 'horus'...
remote: Enumerating objects: 1501, done.
remote: Counting objects: 100% (1501/1501), done.
remote: Compressing objects: 100% (667/667), done.
remote: Total 1501 (delta 957), reused 1363 (delta 819), pack-reused 0
Receiving objects: 100% (1501/1501), 452.31 KiB | 1.75 MiB/s, done.
Resolving deltas: 100% (957/957), done.

make all
go build -ldflags "-X main.Revision== -X main.Build= -X main.Branch=" -o ./cmd/bin ./...
go: downloading github.com/lib/pq v1.2.0
go: downloading github.com/vma/influxclient v1.0.0
go: downloading github.com/jmoiron/sqlx v1.2.0
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading github.com/prometheus/client_golang v1.1.0
go: downloading github.com/mitchellh/copystructure v1.0.0
go: downloading github.com/vma/httplogger v1.0.0
go: downloading github.com/teris-io/shortid v0.0.0-20171029131806-771a37caa5cf
go: downloading github.com/optiopay/kafka/v2 v2.1.1
go: downloading github.com/vma/gosnmp v1.22.4
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/mitchellh/reflectwalk v1.0.0
go: downloading github.com/nats-io/nkeys v0.1.4
go: downloading github.com/prometheus/common v0.6.0
go: downloading github.com/vma/glog v1.5.1
go: downloading github.com/prometheus/procfs v0.0.3
go: downloading github.com/vma/getopt v1.0.0
go: downloading golang.org/x/crypto v0.0.0-20200323165209-0ec3e9974c59
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/golang/mock v1.3.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading github.com/golang/snappy v0.0.1
# github.com/kosctelecom/horus/agent
agent/poll.go:88:5: undefined: updateTotalMem
agent/poll.go:89:5: undefined: updateUsedMem
agent/poll.go:188:15: undefined: usedMem
agent/poll.go:192:78: undefined: usedMem
agent/prometheus.go:108:13: undefined: totalMem
*** Error code 2

Stop.
make: stopped in /data/horus

I have installed Go.

#pkg info | grep go-
go-1.15.9,1                    Go programming language

My OS is :

FreeBSD vma-ingscr-08 12.2-RELEASE-p4 FreeBSD 12.2-RELEASE-p4 GENERIC  amd64

Regards,

Chris.

**Comment by chrisho95** [comment]
Hello,

The problem is that the "make all" command does not work on FreeBsd. Everything is OK on "Centos". I am closing this ticket. 

make all
go build -ldflags "-X main.Revision==v1.4.0 -X main.Build=2021-04-14T09:17:36+0200 -X main.Branch=master" -o ./cmd/bin ./...

cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

Regards,

Christophe.

**Comment by vma** [comment]
Hi Christophe,

Thank you for your report.

The issue is related to syscalls used to get available and used memory by the agent. They are specific to linux, I didn't get the chance to implement related functionality on freebsd yet.

There is actually a mock version available for use on other platform but it looks not up to date. I'll correct it and ask your help to test it.

**Comment by chrisho95** [comment]
Hi,

Ok, I could help you test this version of horus.

I have a question regarding the installation of the database.

Is it possible to install the database on another server ?

The goal is to have a server for the polling part and another which will host the database. 

Regards,

Christophe.

**Comment by vma** [comment]
yes sure, you just have to set the postgres connection string on the dispatcher accordingly i.e. `horus-dispatcher -c postgres://horus:secret@<ip.address.or.hostname>/horus`

**Comment by chrisho95** [comment]
Hi,

Thanks you for your reponses.

Can we launch several agents on different servers or just on one server ?

I saw that we could declare several agents in the agent table. 

If yes, how will the agents know which equipment is polled ? 

Regards,

Christophe.

**Comment by vma** [comment]
Hi,
Yes it was conceived to work on a distributed mode with several agents. The dispatcher loads the list of agents from the db (at startup and regularly) and pings them frequently (via an api request that send back their load) to make sure they are alive and to get their current load. Based on these info, it will send the next polling job (containing the device and list of metrics to poll) to the least loaded agent, skipping dead ones.

The distribution algorithm is actually a little more complicated as there some stickiness to the same agent for the same polled device to reduce memory consumption.

If you have questions specific to your setup, feel free to send me an email (you can find it in my profile). I will be happy to answer.

**Comment by chrisho95** [comment]
Hi,

When polling the horus agent, the dates returned have an offset of 2 hours. Is this normal ?

Example for polling 8h50, the agent returns 6h50.

The date in the server is OK => ven. juin  4 09:01:07 CEST 2021

Regards,

Christophe.

**Comment by vma** [comment]
In db, all dates are in GMT with timezone offset (using postgres type timestamptz). In the code, we use the default go date type which contains the timezone offset as well.

Can you tell me were you see this discrepancy?

**Comment by chrisho95** [comment]
Hello,

The dates in the postgres database are correct.

In contrast, in the exported data, the dates have a 2 hour offset.

For example:

It's 7:42 am and when Horus polishes the data, he sends this back to me for scrape /metrics 

HELP snmp_poll_metric_count number of snmp metrics in poll result
TYPE snmp_poll_metric_count untyped
snmp_poll_metric_count{category="ROUTER",host="xxxxxxxxxxxx",id="2",model="7X50",vendor="ALCATEL"} 14897 1623217344822

1623217344822 corresponds to 5:42 am. We see that there is a difference of 2 hours compared to the server time. 

Regards,

Chris.

**Comment by vma** [comment]
Hi,
all dates in prometheus are in GMT so the timestamp of the exported data is set in GMT also.

**Comment by chrisho95** [comment]
Hi,

Ok but how can I have the exact time because for us it's been 2 hours of lag.

Can I configure prometheus to have the correct time?

**Comment by chrisho95** [comment]
Hi,

In postgres database, the time is OK (GMT +02).

last_pinged_at			lasted_polled_at	
"2021-05-07 17:34:41.102701+02"	"2021-05-07 17:22:02.528472+02"
"2021-06-09 17:23:24.495985+02"	"2021-06-09 17:21:24.50167+02"
"2021-06-09 17:23:24.495985+02"	"2021-06-09 17:22:54.501575+02"
"2021-06-09 17:23:24.495985+02"	"2021-06-09 17:25:24.50127+02"
"2021-06-09 17:23:24.495985+02"	"2021-06-09 17:24:54.502795+02"

But in prometheus data, the time is GMT.

snmp_poll_timeout_count{category="ROUTER",host="**********",id="2",model="7X50",vendor="ALCATEL"} 0 1623252415568

**Comment by chrisho95** [comment]
Hi,
In prometheus, I activated the option "use time local" and now I can see the expected time.

Subject "timestamps" closed.

**Comment by vma** [comment]
good news then!
yes, that's how prometheus works. The conversion to local time is done usually on the grafana dashboard.
